"""
Domain Entity: Alert.

Represents a system-generated alert triggered by risk engine events.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    OPEN = "open"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


@dataclass
class Alert:
    """An alert generated by the AI Risk Engine or anomaly detection."""

    id: UUID = field(default_factory=uuid4)
    supplier_id: UUID = field(default_factory=uuid4)
    title: str = ""
    description: str = ""
    severity: AlertSeverity = AlertSeverity.INFO
    status: AlertStatus = AlertStatus.OPEN
    triggered_at: datetime = field(default_factory=datetime.utcnow)
    resolved_at: Optional[datetime] = None

    def acknowledge(self) -> None:
        """Mark alert as acknowledged by a user."""
        self.status = AlertStatus.ACKNOWLEDGED

    def resolve(self) -> None:
        """Mark alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = datetime.utcnow()

    def is_critical(self) -> bool:
        return self.severity == AlertSeverity.CRITICAL
